# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/misaka10987"

[social.params]
icon = "brand-github"

[[social]]
identifier = "qq"
name = "QQ"
url = "http://2208129531.qzone.qq.com"

[social.params]
icon = "brand-qq"
