baseURL = 'https://misaka10987.github.io/'
languageCode = 'en-us'
title = "misaka10987's pages"
theme = "PaperMod"

[params]
ShowToc = true
TocOpen = true

ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true

ShowPostNavLinks = true

ShowCodeCopyButtons = true

comments = true

editPost = { URL = "https://github.com/misaka10987/misaka10987.github.io/content", Text = "Suggest Changes", appendFilePath = true }

socialIcons = [ { name = "Github", url = "https://github.com/misaka10987" } ]

[params.profileMode]
enabled = true
title = "misaka10987's pages"
subtitle = "Random thoughts."
imageUrl = "https://avatars.githubusercontent.com/u/136697326" # optional
#imageTitle = "<title of image as alt>" # optional
imageWidth = 250                                                             # custom size
imageHeight = 250                                                            # custom size
buttons = [{ name = "Blogs", url = "https://misaka10987.github.io/search" }]

[params.commentsParams]
repo = "misaka10987/misaka10987.github.io"
repoId = "R_kgDOJ1kWxQ"
category = "Announcements"
categoryId = "DIC_kwDOJ1kWxc4CgJQo"
mapping = "specific"
term = "giscus"
strict = 0
reactionsEnabled = 1
emitMetadata = 0
inputPosition = "top"
theme = "preferred_color_scheme"
lang = "en"
loading = "lazy"
crossorigin = "anonymous"

[outputs]
home = ["HTML", "RSS", "JSON"]
